export const MOCK_SYSTEM_NAMES: string[] = [
    'User Authentication Service',
    'Payment Gateway',
    'Notification Service',
    'Inventory Management',
    'Order Processing Pipeline',
    'Customer Relationship Management (CRM)',
    'Analytics & Reporting Engine',
    'Content Delivery Network (CDN)',
    'Primary PostgreSQL Database',
    'Redis Cache Cluster',
    'Search & Indexing Engine',
    'File Storage System (S3)',
    'API Gateway',
    'Monitoring & Telemetry',
    'Audit Logging Service',
    'Recommendation Engine',
    'Billing & Invoicing Service',
    'Fraud Detection System',
    'Identity & Access Management (IAM)',
    'Kafka Event Bus',
    'Media Transcoding Service',
    'Geospatial Location Service',
    'Email Delivery Gateway',
    'Scheduler & Cron Worker',
    'Configuration Management Service',
    'Feature Flag Service',
    'Rate Limiter Service',
    'Webhook Dispatcher',
    'DNS Management Service',
    'Certificate Authority (TLS) Manager',
    'Session Management Service',
    'Event Sourcing Store',
    'GraphQL Federation Gateway',
    'Distributed Locking Service',
    'Secret Management Vault',
    'Log Aggregation Pipeline',
    'Metrics Collector Agent',
    'CI/CD Orchestrator',
    'Container Registry',
    'Load Balancing Controller',
    'Dead Letter Queue Handler',
    'Schema Registry',
    'Blue/Green Deployment Switcher',
    'Backup & Disaster Recovery Worker',
    'Data Anonymization Service',
    'Real-time Collaboration WebSocket Server',
    'User Onboarding Flow Orchestrator',
    'Localization (i18n) Content Delivery Service',
    'API Analytics & Usage Tracker',
    'Health Check & Liveness Probe Service',
];